// Code generated by Slice Machine. DO NOT EDIT.
import { defineSliceZoneComponents } from '@prismicio/vue'
import { defineAsyncComponent } from 'vue'

export const components = defineSliceZoneComponents({
  activity_stats: defineAsyncComponent(
    () => import('./ActivityStats/index.vue'),
  ),
  full_screen_image: defineAsyncComponent(
    () => import('./FullScreenImage/index.vue'),
  ),
  newsletter_subscription: defineAsyncComponent(
    () => import('./NewsletterSubscription/index.vue'),
  ),
  staking_slice: defineAsyncComponent(
    () => import('./StakingSlice/index.vue'),
  ),
  apps_showcase: defineAsyncComponent(
    () => import('./AppsShowcase/index.vue'),
  ),
  gallery_section: defineAsyncComponent(
    () => import('./GallerySection/index.vue'),
  ),
  podcast_platforms: defineAsyncComponent(
    () => import('./PodcastPlatforms/index.vue'),
  ),
  starting_grid: defineAsyncComponent(
    () => import('./StartingGrid/index.vue'),
  ),
  banner_slice: defineAsyncComponent(
    () => import('./BannerSlice/index.vue'),
  ),
  grid_section: defineAsyncComponent(
    () => import('./GridSection/index.vue'),
  ),
  puzzle_grid: defineAsyncComponent(
    () => import('./PuzzleGrid/index.vue'),
  ),
  stepped_lottie: defineAsyncComponent(
    () => import('./SteppedLottie/index.vue'),
  ),
  blogposts_grid: defineAsyncComponent(
    () => import('./BlogpostsGrid/index.vue'),
  ),
  hero_section: defineAsyncComponent(
    () => import('./HeroSection/index.vue'),
  ),
  rib_cage_grid: defineAsyncComponent(
    () => import('./RibCageGrid/index.vue'),
  ),
  stepped_slides: defineAsyncComponent(
    () => import('./SteppedSlides/index.vue'),
  ),
  buy_sell_wallet: defineAsyncComponent(
    () => import('./BuySellWallet/index.vue'),
  ),
  hero_stats: defineAsyncComponent(
    () => import('./HeroStats/index.vue'),
  ),
  rich_text: defineAsyncComponent(
    () => import('./RichText/index.vue'),
  ),
  supply_distribution: defineAsyncComponent(
    () => import('./SupplyDistribution/index.vue'),
  ),
  cards_carousel: defineAsyncComponent(
    () => import('./CardsCarousel/index.vue'),
  ),
  iframe_embed: defineAsyncComponent(
    () => import('./IframeEmbed/index.vue'),
  ),
  rich_text_cards: defineAsyncComponent(
    () => import('./RichTextCards/index.vue'),
  ),
  team_members: defineAsyncComponent(
    () => import('./TeamMembers/index.vue'),
  ),
  consensus_map: defineAsyncComponent(
    () => import('./ConsensusMap/index.vue'),
  ),
  large_grid: defineAsyncComponent(
    () => import('./LargeGrid/index.vue'),
  ),
  rich_text_carousel: defineAsyncComponent(
    () => import('./RichTextCarousel/index.vue'),
  ),
  tilted_media: defineAsyncComponent(
    () => import('./TiltedMedia/index.vue'),
  ),
  contact_form: defineAsyncComponent(
    () => import('./ContactForm/index.vue'),
  ),
  latest_blogpost: defineAsyncComponent(
    () => import('./LatestBlogpost/index.vue'),
  ),
  roadmap_section: defineAsyncComponent(
    () => import('./RoadmapSection/index.vue'),
  ),
  tweets_marquee: defineAsyncComponent(
    () => import('./TweetsMarquee/index.vue'),
  ),
  cta_section: defineAsyncComponent(
    () => import('./CtaSection/index.vue'),
  ),
  link_grid: defineAsyncComponent(
    () => import('./LinkGrid/index.vue'),
  ),
  s3_currency_banner: defineAsyncComponent(
    () => import('./S3CurrencyBanner/index.vue'),
  ),
  whitepaper_slice: defineAsyncComponent(
    () => import('./WhitepaperSlice/index.vue'),
  ),
  exchanges_showcase: defineAsyncComponent(
    () => import('./ExchangesShowcase/index.vue'),
  ),
  logos_grid: defineAsyncComponent(
    () => import('./LogosGrid/index.vue'),
  ),
  simple_carousel: defineAsyncComponent(
    () => import('./SimpleCarousel/index.vue'),
  ),
  youtube_video: defineAsyncComponent(
    () => import('./YoutubeVideo/index.vue'),
  ),
  flags_marquee: defineAsyncComponent(
    () => import('./FlagsMarquee/index.vue'),
  ),
  lottie_slice: defineAsyncComponent(
    () => import('./LottieSlice/index.vue'),
  ),
  simple_headline: defineAsyncComponent(
    () => import('./SimpleHeadline/index.vue'),
  ),
  zig_zag_content: defineAsyncComponent(
    () => import('./ZigZagContent/index.vue'),
  ),
  floating_video: defineAsyncComponent(
    () => import('./FloatingVideo/index.vue'),
  ),
  new_york_grid: defineAsyncComponent(
    () => import('./NewYorkGrid/index.vue'),
  ),
  social_media_grid: defineAsyncComponent(
    () => import('./SocialMediaGrid/index.vue'),
  ),
})
