catalog:
  '@antfu/eslint-config': ^4.12.0
  '@iconify-json/logos': ^1.2.4
  '@iconify/utils': ^2.3.0
  '@iconify/vue': ^4.3.0
  '@nimiq/core': ^2.0.9
  '@nimiq/utils': ^0.12.3
  '@nuxt/eslint': latest
  '@nuxt/fonts': ^0.11.2
  '@nuxt/icon': ^1.12.0
  '@nuxt/image': ^1.10.0
  '@nuxthub/core': ^0.8.25
  '@nuxtjs/critters': ^0.9.0
  '@nuxtjs/device': ^3.2.4
  '@nuxtjs/prismic': ^4.1.0
  '@nuxtjs/seo': 3.0.3
  '@pinia/colada': ^0.15.1
  '@pinia/colada-nuxt': ^0.1.3
  '@pinia/nuxt': ^0.11.0
  '@popperjs/core': ^2.11.8
  '@prismicio/client': ^7.17.2
  '@prismicio/richtext': ^2.1.5
  '@slicemachine/adapter-nuxt': ^0.3.75
  '@types/node': ^22.15.2
  '@unocss/eslint-plugin': ^66.1.0-beta.12
  '@unocss/nuxt': ^66.1.0-beta.12
  '@unocss/reset': ^66.1.0-beta.12
  '@unovis/ts': 1.5.1
  '@unovis/vue': 1.5.1
  '@vueuse/core': ^13.1.0
  '@vueuse/motion': ^3.0.3
  '@vueuse/nuxt': ^13.1.0
  '@vueuse/router': ^13.1.0
  cookie: ^1.0.2
  eslint: ^9.25.1
  eslint-plugin-format: ^1.0.1
  hero-motion: ^0.5.3
  lint-staged: ^15.5.1
  medium-zoom: ^1.1.0
  nimiq-css: ^1.0.0-beta.20
  nimiq-icons: ^1.0.0-beta.20
  nimiq-rpc-client-ts: https://pkg.pr.new/onmax/albatross-rpc-client-ts/nimiq-rpc-client-ts@7618575
  nuxt: ^3.17.0
  pathe: ^2.0.3
  pinia: ^3.0.2
  reka-ui: ^2.2.0
  sharp: ^0.34.1
  simple-git-hooks: ^2.13.0
  slice-machine-ui: ^2.15.2
  typescript: ^5.8.3
  unocss: ^66.1.0-beta.12
  unocss-preset-onmax: ^1.0.0-beta.16
  unocss-preset-scale-px: 1.0.0-beta.16
  unplugin-vue-router: ^0.12.0
  valibot: ^1.0.0
  vaul-vue: ^0.4.1
  vite-plugin-top-level-await: ^1.5.0
  vite-plugin-wasm: ^3.4.1
  vue: latest
  vue-router: ^4.5.1
  vue3-lottie: ^3.3.1
  wrangler: ^4.13.2

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@swc/core'
  - bufferutil
  - es5-ext
  - esbuild
  - maplibre-gl
  - sharp
  - simple-git-hooks
  - unrs-resolver
  - utf-8-validate
  - vue-demi
  - workerd
