packages:
  - ./
patchedDependencies:
  '@nuxt/content': patches/@nuxt__content.patch
catalog:
  '@nuxt/content': ^3.9.0
  '@nuxt/hints': 1.0.0-alpha.3
  '@nuxthub/core': 0.10.1
  '@nuxtjs/tailwindcss': 7.0.0-beta.1
  '@types/js-yaml': ^4.0.9
  '@vitest/browser': ^4.0.16
  '@vitest/ui': ^4.0.16
  dotenv: ^17.2.3
  js-yaml: ^4.1.0
  marked: ^17.0.1
  mdream: ^0.15.3
  nuxt-link-checker: ^4.3.9
  nuxt-studio: 1.0.0-beta.0
  pixelmatch: ^7.1.0
  playwright: ^1.57.0
  pngjs: ^7.0.0
  tsx: ^4.20.6
  unist-util-visit: ^5.0.0
  vitest: ^4.0.16
catalogs:
  build:
    '@nuxt/kit': ^4.0.0
    vite-plugin-wasm: ^3.4.1
    wrangler: ^4.15.2
  frontend:
    '@unovis/ts': 1.5.1
    '@unovis/vue': 1.5.1
    '@vueuse/core': ^13.5.0
    '@vueuse/nuxt': ^13.5.0
    '@vueuse/router': ^13.5.0
    medium-zoom: ^1.1.0
    motion-v: ^1.5.0
    reka-ui: ^2.2.1
    vaul-vue: ^0.4.1
    vue: latest
    vue-router: ^4.5.1
    vue-tsc: ^2.2.10
  lint:
    '@antfu/eslint-config': ^5.4.1
    '@nuxt/eslint': latest
    eslint: ^9.37.0
    eslint-plugin-format: ^1.0.2
    lint-staged: ^16.2.3
    simple-git-hooks: ^2.13.1
  nimiq:
    '@nimiq/core': ^2.1.1
    '@nimiq/utils': ^0.12.4
    nimiq-icons: ^1.0.0-beta.160
    nimiq-rpc-client-ts: ^1.0.0-beta.35
  nuxt:
    '@nuxt/icon': ^2.1.1
    '@nuxt/image': 2.0.0-alpha.1
    '@nuxt/scripts': ^0.11.10
    '@nuxtjs/device': ^3.2.4
    '@nuxtjs/seo': ^3.1.0
    nuxt: ^4.2.0
    nuxt-module-feed: ^1.1.4
    nuxt-safe-runtime-config: ^0.0.3
  prismic:
    '@prismicio/client': ^7.17.2
    '@prismicio/richtext': ^2.1.5
  server:
    consola: ^3.4.2
    sharp: ^0.34.1
    valibot: ^1.1.0
  studio:
    drizzle-kit: ^0.30.5
    drizzle-orm: ^0.38.3
  types:
    '@types/node': ^22.15.19
    typescript: ^5.8.3
onlyBuiltDependencies:
  - better-sqlite3
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@swc/core'
  - bufferutil
  - es5-ext
  - esbuild
  - maplibre-gl
  - simple-git-hooks
  - sharp
  - unrs-resolver
  - utf-8-validate
  - vue-demi
  - workerd
