packages:
  - base
  - liveview
catalog:
  'nuxt': '^3.13.0'
  'nimiq-rpc-client-ts': 'https://pkg.pr.new/onmax/albatross-rpc-client-ts/nimiq-rpc-client-ts@7618575'
  '@nimiq/core': 'next'
  '@nimiq/utils': '^0.11.3'
  'typescript': '^5.5.4'
  '@nuxthub/core': '^0.7.9'
