packages:
  - ./
patchedDependencies:
  '@nimiq/utils': patches/@nimiq__utils.patch
catalogs:
  build:
    '@nuxt/kit': ^4.0.0
    vite-plugin-top-level-await: ^1.5.0
    vite-plugin-wasm: ^3.4.1
    wrangler: ^4.15.2
  frontend:
    '@pinia/colada': ^0.15.3
    '@pinia/colada-nuxt': ^0.1.3
    '@pinia/colada-plugin-delay': ^0.0.6
    '@pinia/nuxt': ^0.11.1
    '@unovis/ts': 1.5.1
    '@unovis/vue': 1.5.1
    '@vueuse/core': ^13.5.0
    '@vueuse/nuxt': ^13.5.0
    '@vueuse/router': ^13.5.0
    medium-zoom: ^1.1.0
    motion-v: ^1.5.0
    pinia: ^3.0.3
    reka-ui: ^2.2.1
    vaul-vue: ^0.4.1
    vue: latest
    vue-router: ^4.5.1
    vue-tsc: ^2.2.10
  lint:
    '@antfu/eslint-config': ^4.13.1
    '@nuxt/eslint': latest
    '@unocss/eslint-plugin': ^66.1.2
    eslint: ^9.27.0
    eslint-plugin-format: ^1.0.1
    lint-staged: ^16.0.0
    simple-git-hooks: ^2.13.0
  nimiq:
    '@nimiq/core': ^2.1.1
    '@nimiq/utils': ^0.12.4
    nimiq-rpc-client-ts: ^1.0.0-beta.35
  nuxt:
    '@nuxt/fonts': ^0.11.4
    '@nuxt/image': 2.0.0-alpha.1
    '@nuxt/scripts': ^0.11.10
    '@nuxthub/core': ^0.9.0
    '@nuxtjs/device': ^3.2.4
    '@nuxtjs/prismic': ^4.1.0
    '@nuxtjs/seo': ^3.1.0
    nuxt: ^4.0.0
    nuxt-module-feed: ^1.1.4
    nuxt-safe-runtime-config: ^0.0.3
    unplugin-vue-router: ^0.12.0
  prismic:
    '@prismicio/client': ^7.17.2
    '@prismicio/richtext': ^2.1.5
    '@slicemachine/adapter-nuxt': 0.3.81-alpha.lh-nuxt-4-support.2
    slice-machine-ui: ^2.16.0
  server:
    consola: ^3.4.2
    sharp: ^0.34.1
    valibot: ^1.1.0
  types:
    '@types/node': ^22.15.19
    typescript: ^5.8.3
  unocss:
    '@iconify-json/logos': ^1.2.4
    '@iconify/utils': ^2.3.0
    '@unocss/nuxt': ^66.1.2
    '@unocss/preset-wind4': ^66.1.2
    '@unocss/reset': ^66.1.2
    nimiq-css: ^1.0.0-beta.30
    nimiq-flags: ^1.0.0-beta.30
    nimiq-icons: ^1.0.0-beta.30
    unocss: ^66.1.2
    unocss-preset-onmax: ^1.0.0-beta.25
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@swc/core'
  - bufferutil
  - es5-ext
  - esbuild
  - maplibre-gl
  - simple-git-hooks
  - sharp
  - unrs-resolver
  - utf-8-validate
  - vue-demi
  - workerd
