// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

/**
 * Item in *Blog Article → Authors*
 */
export interface BlogPageDocumentDataAuthorsItem {
  /**
   * Name field in *Blog Article → Authors*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_page.authors[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField
}

type BlogPageDocumentDataBodySlice = never

/**
 * Content for Blog Article documents
 */
interface BlogPageDocumentData {
  /**
   * Draft field in *Blog Article*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: blog_page.draft
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  draft: prismic.BooleanField

  /**
   * Title field in *Blog Article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField

  /**
   * Introduction field in *Blog Article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_page.subline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subline: prismic.RichTextField

  /**
   * Publish date field in *Blog Article*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_page.publish_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  publish_date: prismic.DateField

  /**
   * Authors field in *Blog Article*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_page.authors[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  authors: prismic.GroupField<Simplify<BlogPageDocumentDataAuthorsItem>>

  /**
   * Image field in *Blog Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_page.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Text (Deprecated - Use SliceZone instead) field in *Blog Article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_page.text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField

  /**
   * Slice Zone field in *Blog Article*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_page.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  body: prismic.SliceZone<BlogPageDocumentDataBodySlice> /**
                                                          * Meta title field in *Blog Article*
                                                          *
                                                          * - **Field Type**: Text
                                                          * - **Placeholder**: Uses blog title if not set
                                                          * - **API ID Path**: blog_page.meta_title
                                                          * - **Tab**: Meta & SEO
                                                          * - **Documentation**: https://prismic.io/docs/field#key-text
                                                          */
  meta_title: prismic.KeyTextField

  /**
   * Meta description field in *Blog Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Uses blog introduction if not set
   * - **API ID Path**: blog_page.meta_description
   * - **Tab**: Meta & SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta keywords field in *Blog Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Uses default keywords if unset. Example: keyword1, keyword2, keyword3
   * - **API ID Path**: blog_page.meta_keywords
   * - **Tab**: Meta & SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_keywords: prismic.KeyTextField

  /**
   * Social Media Preview (uses blog image if unset) field in *Blog Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_page.meta_image
   * - **Tab**: Meta & SEO
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>
}

/**
 * Blog Article document from Prismic
 *
 * - **API ID**: `blog_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPageDocumentData>,
    'blog_page',
    Lang
  >

type ChildPageDocumentDataSlicesSlice = never

/**
 * Content for Child Page documents
 */
interface ChildPageDocumentData {
  /**
   * Draft field in *Child Page*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: child_page.draft
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  draft: prismic.BooleanField

  /**
   * Parent Page field in *Child Page*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: child_page.parent
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  parent: prismic.ContentRelationshipField<'page'>

  /**
   * Header background color field in *Child Page*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: white
   * - **API ID Path**: child_page.headerBackgroundColor
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  headerBackgroundColor: prismic.SelectField<
    'white' | 'grey' | 'blue-dark' | 'blue' | 'green' | 'blue-s3',
    'filled'
  >

  /**
   * Footer background color field in *Child Page*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: white
   * - **API ID Path**: child_page.footerBackgroundColor
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  footerBackgroundColor: prismic.SelectField<
    'white' | 'grey' | 'blue-dark',
    'filled'
  >

  /**
   * Show table of contents field in *Child Page*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: child_page.show_table_of_contents
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  show_table_of_contents: prismic.SelectField<
    'None' | 'Short (Only h2)' | 'Long (h2 and h3)',
    'filled'
  >

  /**
   * Show Disclaimer field in *Child Page*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: child_page.show_disclaimer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  show_disclaimer: prismic.BooleanField

  /**
   * Slice Zone field in *Child Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: child_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ChildPageDocumentDataSlicesSlice> /**
                                                               * Meta title field in *Child Page*
                                                               *
                                                               * - **Field Type**: Text
                                                               * - **Placeholder**: Used default title if unset
                                                               * - **API ID Path**: child_page.meta_title
                                                               * - **Tab**: Meta & SEO
                                                               * - **Documentation**: https://prismic.io/docs/field#key-text
                                                               */
  meta_title: prismic.KeyTextField

  /**
   * Meta description field in *Child Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Used default description if unset
   * - **API ID Path**: child_page.meta_description
   * - **Tab**: Meta & SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta keywords field in *Child Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Used default keywords if unset. Example: keyword1, keyword2, keyword3
   * - **API ID Path**: child_page.meta_keywords
   * - **Tab**: Meta & SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_keywords: prismic.KeyTextField

  /**
   * Social Media Preview (uses default image if unset) field in *Child Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: child_page.meta_image
   * - **Tab**: Meta & SEO
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>
}

/**
 * Child Page document from Prismic
 *
 * - **API ID**: `child_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ChildPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ChildPageDocumentData>,
    'child_page',
    Lang
  >

type HomeDocumentDataBodySlice = never

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Header background color field in *Home*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: white
   * - **API ID Path**: home.headerBackgroundColor
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  headerBackgroundColor: prismic.SelectField<
    'white' | 'grey' | 'blue-dark' | 'blue' | 'green',
    'filled'
  >

  /**
   * Footer background color field in *Home*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: white
   * - **API ID Path**: home.footerBackgroundColor
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  footerBackgroundColor: prismic.SelectField<
    'white' | 'grey' | 'blue-dark',
    'filled'
  >

  /**
   * Slice zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  body: prismic.SliceZone<HomeDocumentDataBodySlice> /**
                                                      * Meta title field in *Home*
                                                      *
                                                      * - **Field Type**: Text
                                                      * - **Placeholder**: Used default title if unset
                                                      * - **API ID Path**: home.meta_title
                                                      * - **Tab**: Meta & SEO
                                                      * - **Documentation**: https://prismic.io/docs/field#key-text
                                                      */
  meta_title: prismic.KeyTextField

  /**
   * Meta description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Used default description if unset
   * - **API ID Path**: home.meta_description
   * - **Tab**: Meta & SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta keywords field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Used default keywords if unset. Example: keyword1, keyword2, keyword3
   * - **API ID Path**: home.meta_keywords
   * - **Tab**: Meta & SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_keywords: prismic.KeyTextField

  /**
   * Social Media Preview (uses default image if unset) field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: Meta & SEO
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, 'home', Lang>

type Home2024DocumentDataSlicesSlice = never

/**
 * Content for Home 2024 documents
 */
interface Home2024DocumentData {
  /**
   * Slice Zone field in *Home 2024*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_2024.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<Home2024DocumentDataSlicesSlice> /**
                                                              * Meta Title field in *Home 2024*
                                                              *
                                                              * - **Field Type**: Text
                                                              * - **Placeholder**: A title of the page used for social media and search engines
                                                              * - **API ID Path**: home_2024.meta_title
                                                              * - **Tab**: SEO & Metadata
                                                              * - **Documentation**: https://prismic.io/docs/field#key-text
                                                              */
  meta_title: prismic.KeyTextField

  /**
   * Meta Description field in *Home 2024*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_2024.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Home 2024*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_2024.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>
}

/**
 * Home 2024 document from Prismic
 *
 * - **API ID**: `home_2024`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type Home2024Document<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<Home2024DocumentData>,
    'home_2024',
    Lang
  >

/**
 * Item in *Navigation → Apps**
 */
export interface NavigationDocumentDataAppsLinksItem {
  /**
   * Logo* field in *Navigation → Apps**
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.appsLinks[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>

  /**
   * Screenshot/visual of the app* field in *Navigation → Apps**
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.appsLinks[].visual
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  visual: prismic.ImageField<never>

  /**
   * Label* field in *Navigation → Apps**
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.appsLinks[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField

  /**
   * Link href* field in *Navigation → Apps**
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.appsLinks[].href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  href: prismic.LinkField
}

/**
 * Item in *Navigation → How to links**
 */
export interface NavigationDocumentDataHowToLinksItem {
  /**
   * Link href* field in *Navigation → How to links**
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.howToLinks[].href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  href: prismic.LinkField

  /**
   * Link label* field in *Navigation → How to links**
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.howToLinks[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField
}

/**
 * Item in *Navigation → Apps additional footer links*
 */
export interface NavigationDocumentDataAppsAdditionalFooterLinksItem {
  /**
   * Link href* field in *Navigation → Apps additional footer links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.appsAdditionalFooterLinks[].href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  href: prismic.LinkField

  /**
   * Link label* field in *Navigation → Apps additional footer links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.appsAdditionalFooterLinks[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField
}

/**
 * Item in *Navigation → Tech links**
 */
export interface NavigationDocumentDataTechLinksItem {
  /**
   * Link href* field in *Navigation → Tech links**
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.techLinks[].href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  href: prismic.LinkField

  /**
   * Link label* field in *Navigation → Tech links**
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.techLinks[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField
}

/**
 * Item in *Navigation → Tech additional footer links*
 */
export interface NavigationDocumentDataTechAdditionalFooterLinksItem {
  /**
   * Link href* field in *Navigation → Tech additional footer links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.techAdditionalFooterLinks[].href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  href: prismic.LinkField

  /**
   * Link label* field in *Navigation → Tech additional footer links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.techAdditionalFooterLinks[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField
}

/**
 * Item in *Navigation → Community links**
 */
export interface NavigationDocumentDataCommunityLinksItem {
  /**
   * Link href* field in *Navigation → Community links**
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.communityLinks[].href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  href: prismic.LinkField

  /**
   * Link label* field in *Navigation → Community links**
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.communityLinks[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField
}

/**
 * Item in *Navigation → Community additional footer links*
 */
export interface NavigationDocumentDataCommunityAdditionalFooterLinksItem {
  /**
   * Link href* field in *Navigation → Community additional footer links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.communityAdditionalFooterLinks[].href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  href: prismic.LinkField

  /**
   * Link label* field in *Navigation → Community additional footer links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.communityAdditionalFooterLinks[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField
}

/**
 * Item in *Navigation → Project links**
 */
export interface NavigationDocumentDataProjectLinksItem {
  /**
   * Link href* field in *Navigation → Project links**
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.projectLinks[].href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  href: prismic.LinkField

  /**
   * Link label* field in *Navigation → Project links**
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.projectLinks[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField
}

/**
 * Item in *Navigation → Project additional footer links*
 */
export interface NavigationDocumentDataProjectAdditionalFooterLinksItem {
  /**
   * Link href* field in *Navigation → Project additional footer links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.projectAdditionalFooterLinks[].href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  href: prismic.LinkField

  /**
   * Link label* field in *Navigation → Project additional footer links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.projectAdditionalFooterLinks[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField
}

/**
 * Item in *Navigation → Get started links**
 */
export interface NavigationDocumentDataGetStartedLinksItem {
  /**
   * Link href* field in *Navigation → Get started links**
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.getStartedLinks[].href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  href: prismic.LinkField

  /**
   * Link label* field in *Navigation → Get started links**
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.getStartedLinks[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField

  /**
   * Description* field in *Navigation → Get started links**
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.getStartedLinks[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField
}

/**
 * Item in *Navigation → New to crypto links**
 */
export interface NavigationDocumentDataNewToCryptoLinksItem {
  /**
   * Link href* field in *Navigation → New to crypto links**
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.newToCryptoLinks[].href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  href: prismic.LinkField

  /**
   * Link label* field in *Navigation → New to crypto links**
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.newToCryptoLinks[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField
}

/**
 * Item in *Navigation → Get started additional footer links*
 */
export interface NavigationDocumentDataGetStartedAdditionalFooterLinksItem {
  /**
   * Link href* field in *Navigation → Get started additional footer links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.getStartedAdditionalFooterLinks[].href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  href: prismic.LinkField

  /**
   * Link label* field in *Navigation → Get started additional footer links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.getStartedAdditionalFooterLinks[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField
}

/**
 * Item in *Navigation → ...and more links**
 */
export interface NavigationDocumentDataAndMoreLinksItem {
  /**
   * Link href* field in *Navigation → ...and more links**
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.andMoreLinks[].href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  href: prismic.LinkField

  /**
   * Link label* field in *Navigation → ...and more links**
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.andMoreLinks[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField
}

/**
 * Item in *Navigation → Legal pages links*
 */
export interface NavigationDocumentDataLegalPagesItem {
  /**
   * Link href* field in *Navigation → Legal pages links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.legalPages[].href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  href: prismic.LinkField

  /**
   * Link label* field in *Navigation → Legal pages links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.legalPages[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField
}

/**
 * Item in *Navigation → Extra header links*
 */
export interface NavigationDocumentDataExtraHeaderLinksItem {
  /**
   * Link href* field in *Navigation → Extra header links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.extraHeaderLinks[].href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  href: prismic.LinkField

  /**
   * Link label* field in *Navigation → Extra header links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.extraHeaderLinks[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Apps link group name* field in *Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Apps
   * - **API ID Path**: navigation.appsGroupName
   * - **Tab**: Apps
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  appsGroupName: prismic.KeyTextField

  /**
   * Apps* field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.appsLinks[]
   * - **Tab**: Apps
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  appsLinks: prismic.GroupField<Simplify<NavigationDocumentDataAppsLinksItem>>

  /**
   * How to section title field in *Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: How to
   * - **API ID Path**: navigation.howToTitle
   * - **Tab**: Apps
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  howToTitle: prismic.KeyTextField

  /**
   * How to links* field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.howToLinks[]
   * - **Tab**: Apps
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  howToLinks: prismic.GroupField<
    Simplify<NavigationDocumentDataHowToLinksItem>
  >

  /**
   * Apps additional footer links field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.appsAdditionalFooterLinks[]
   * - **Tab**: Apps
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  appsAdditionalFooterLinks: prismic.GroupField<
    Simplify<NavigationDocumentDataAppsAdditionalFooterLinksItem>
  > /**
     * Tech link group name* field in *Navigation*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Tech
     * - **API ID Path**: navigation.techGroupName
     * - **Tab**: Tech
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
  techGroupName: prismic.KeyTextField

  /**
   * Tech links* field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.techLinks[]
   * - **Tab**: Tech
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  techLinks: prismic.GroupField<Simplify<NavigationDocumentDataTechLinksItem>>

  /**
   * Github link label* field in *Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.githubLinkLabel
   * - **Tab**: Tech
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  githubLinkLabel: prismic.KeyTextField

  /**
   * Tech additional footer links field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.techAdditionalFooterLinks[]
   * - **Tab**: Tech
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  techAdditionalFooterLinks: prismic.GroupField<
    Simplify<NavigationDocumentDataTechAdditionalFooterLinksItem>
  > /**
     * Community link group name* field in *Navigation*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Community
     * - **API ID Path**: navigation.communityGroupName
     * - **Tab**: Community
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
  communityGroupName: prismic.KeyTextField

  /**
   * Community links* field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.communityLinks[]
   * - **Tab**: Community
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  communityLinks: prismic.GroupField<
    Simplify<NavigationDocumentDataCommunityLinksItem>
  >

  /**
   * Community additional footer links field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.communityAdditionalFooterLinks[]
   * - **Tab**: Community
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  communityAdditionalFooterLinks: prismic.GroupField<
    Simplify<NavigationDocumentDataCommunityAdditionalFooterLinksItem>
  > /**
     * Project link group name* field in *Navigation*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Project
     * - **API ID Path**: navigation.projectGroupName
     * - **Tab**: Project
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
  projectGroupName: prismic.KeyTextField

  /**
   * Project links* field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.projectLinks[]
   * - **Tab**: Project
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  projectLinks: prismic.GroupField<
    Simplify<NavigationDocumentDataProjectLinksItem>
  >

  /**
   * Project additional footer links field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.projectAdditionalFooterLinks[]
   * - **Tab**: Project
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  projectAdditionalFooterLinks: prismic.GroupField<
    Simplify<NavigationDocumentDataProjectAdditionalFooterLinksItem>
  > /**
     * Get started link group name* field in *Navigation*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Get started
     * - **API ID Path**: navigation.getStartedGroupName
     * - **Tab**: Get Started
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
  getStartedGroupName: prismic.KeyTextField

  /**
   * Get started links* field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.getStartedLinks[]
   * - **Tab**: Get Started
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  getStartedLinks: prismic.GroupField<
    Simplify<NavigationDocumentDataGetStartedLinksItem>
  >

  /**
   * New to crypto section title field in *Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: New to crypto
   * - **API ID Path**: navigation.newToCryptoTitle
   * - **Tab**: Get Started
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  newToCryptoTitle: prismic.KeyTextField

  /**
   * New to crypto links* field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.newToCryptoLinks[]
   * - **Tab**: Get Started
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  newToCryptoLinks: prismic.GroupField<
    Simplify<NavigationDocumentDataNewToCryptoLinksItem>
  >

  /**
   * Get started additional footer links field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.getStartedAdditionalFooterLinks[]
   * - **Tab**: Get Started
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  getStartedAdditionalFooterLinks: prismic.GroupField<
    Simplify<NavigationDocumentDataGetStartedAdditionalFooterLinksItem>
  > /**
     * ...and more link group name* field in *Navigation*
     *
     * - **Field Type**: Text
     * - **Placeholder**: ...and more
     * - **API ID Path**: navigation.andMoreGroupName
     * - **Tab**: ...and more
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
  andMoreGroupName: prismic.KeyTextField

  /**
   * ...and more links* field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.andMoreLinks[]
   * - **Tab**: ...and more
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  andMoreLinks: prismic.GroupField<
    Simplify<NavigationDocumentDataAndMoreLinksItem>
  > /**
     * Legal pages links field in *Navigation*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.legalPages[]
     * - **Tab**: Legal pages
     * - **Documentation**: https://prismic.io/docs/field#group
     */
  legalPages: prismic.GroupField<
    Simplify<NavigationDocumentDataLegalPagesItem>
  > /**
     * Extra header links field in *Navigation*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.extraHeaderLinks[]
     * - **Tab**: Miscellaneous
     * - **Documentation**: https://prismic.io/docs/field#group
     */
  extraHeaderLinks: prismic.GroupField<
    Simplify<NavigationDocumentDataExtraHeaderLinksItem>
  >

  /**
   * Newsletter CTA field in *Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.newsletterCta
   * - **Tab**: Miscellaneous
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  newsletterCta: prismic.KeyTextField

  /**
   * Newsletter placeholder field in *Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.newsletterPlaceholder
   * - **Tab**: Miscellaneous
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  newsletterPlaceholder: prismic.KeyTextField

  /**
   * Social media CTA field in *Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.socialMediaCta
   * - **Tab**: Miscellaneous
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  socialMediaCta: prismic.KeyTextField

  /**
   * Nimiq short description field in *Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.nimiqShortDescription
   * - **Tab**: Miscellaneous
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nimiqShortDescription: prismic.KeyTextField /**
                                               * href* field in *Navigation*
                                               *
                                               * - **Field Type**: Link
                                               * - **Placeholder**: *None*
                                               * - **API ID Path**: navigation.hothref
                                               * - **Tab**: 🔥 HOT
                                               * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
                                               */
  hothref: prismic.LinkField

  /**
   * text* field in *Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.hottext
   * - **Tab**: 🔥 HOT
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hottext: prismic.KeyTextField

  /**
   * since field in *Navigation*
   *
   * - **Field Type**: Date
   * - **Placeholder**: since when it should show. Optional
   * - **API ID Path**: navigation.hotsince
   * - **Tab**: 🔥 HOT
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  hotsince: prismic.DateField

  /**
   * until field in *Navigation*
   *
   * - **Field Type**: Date
   * - **Placeholder**: until when it should show. Optional
   * - **API ID Path**: navigation.hotuntil
   * - **Tab**: 🔥 HOT
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  hotuntil: prismic.DateField
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    'navigation',
    Lang
  >

/**
 * Content for App documents
 */
interface NimiqAppDocumentData {
  /**
   * Is this an highlighted app? field in *App*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: nimiq_app.isHighlighted
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  isHighlighted: prismic.BooleanField

  /**
   * Is this an official app? field in *App*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: nimiq_app.isOfficial
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  isOfficial: prismic.BooleanField

  /**
   * Name* field in *App*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nimiq_app.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField

  /**
   * Description* field in *App*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nimiq_app.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * Link Href* field in *App*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: nimiq_app.linkHref
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkHref: prismic.LinkField

  /**
   * Type field in *App*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: nimiq_app.type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<
    | 'Insights'
    | 'E-commerce'
    | 'Games'
    | 'Faucet'
    | 'Promotion'
    | 'Miner'
    | 'Wallets'
    | 'Infrastructure'
    | 'Bots'
  >

  /**
   * Logo (.svg) field in *App*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nimiq_app.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>

  /**
   * Priority Level field in *App*
   *
   * - **Field Type**: Select
   * - **Placeholder**: High: Will be shown first in lists. Medium and low: will be shown after
   * - **Default Value**: low
   * - **API ID Path**: nimiq_app.priority_level
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  priority_level: prismic.SelectField<'low' | 'medium' | 'high', 'filled'> /**
                                                                            * Screenshot field in *App*
                                                                            *
                                                                            * - **Field Type**: Image
                                                                            * - **Placeholder**: *None*
                                                                            * - **API ID Path**: nimiq_app.screenshot
                                                                            * - **Tab**: Official App
                                                                            * - **Documentation**: https://prismic.io/docs/field#image
                                                                            */
  screenshot: prismic.ImageField<never> /**
                                         * developer field in *App*
                                         *
                                         * - **Field Type**: Text
                                         * - **Placeholder**: *None*
                                         * - **API ID Path**: nimiq_app.developer
                                         * - **Tab**: Community App
                                         * - **Documentation**: https://prismic.io/docs/field#key-text
                                         */
  developer: prismic.KeyTextField
}

/**
 * App document from Prismic
 *
 * - **API ID**: `nimiq_app`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NimiqAppDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NimiqAppDocumentData>,
    'nimiq_app',
    Lang
  >

/**
 * Content for Event documents
 */
interface NimiqEventDocumentData {
  /**
   * image field in *Event*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nimiq_event.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * title field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nimiq_event.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * short description field in *Event*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nimiq_event.short_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  short_description: prismic.RichTextField

  /**
   * startDate field in *Event*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: nimiq_event.start_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  start_date: prismic.DateField

  /**
   * endDate field in *Event*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: nimiq_event.end_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  end_date: prismic.DateField

  /**
   * location field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nimiq_event.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  location: prismic.KeyTextField

  /**
   * linkHref field in *Event*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: nimiq_event.linkhref
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkhref: prismic.LinkField
}

/**
 * Event document from Prismic
 *
 * - **API ID**: `nimiq_event`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NimiqEventDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NimiqEventDocumentData>,
    'nimiq_event',
    Lang
  >

type PageDocumentDataSlicesSlice = never

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Draft field in *Page*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: page.draft
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  draft: prismic.BooleanField

  /**
   * Header background color field in *Page*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: white
   * - **API ID Path**: page.headerBackgroundColor
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  headerBackgroundColor: prismic.SelectField<
    'white' | 'grey' | 'blue-dark' | 'blue' | 'green' | 'blue-s3',
    'filled'
  >

  /**
   * Footer background color field in *Page*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: white
   * - **API ID Path**: page.footerBackgroundColor
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  footerBackgroundColor: prismic.SelectField<
    'white' | 'grey' | 'blue-dark',
    'filled'
  >

  /**
   * Show table of contents field in *Page*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: page.show_table_of_contents
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  show_table_of_contents: prismic.SelectField<
    'None' | 'Short (Only h2)' | 'Long (h2 and h3)',
    'filled'
  >

  /**
   * Show Disclaimer field in *Page*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: page.show_disclaimer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  show_disclaimer: prismic.BooleanField

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
                                                          * Meta title field in *Page*
                                                          *
                                                          * - **Field Type**: Text
                                                          * - **Placeholder**: Uses default title if unset
                                                          * - **API ID Path**: page.meta_title
                                                          * - **Tab**: Meta & SEO
                                                          * - **Documentation**: https://prismic.io/docs/field#key-text
                                                          */
  meta_title: prismic.KeyTextField

  /**
   * Meta description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Uses default description if unset
   * - **API ID Path**: page.meta_description
   * - **Tab**: Meta & SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta keywords field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Uses default keywords if unset. Example: keyword1, keyword2, keyword3
   * - **API ID Path**: page.meta_keywords
   * - **Tab**: Meta & SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_keywords: prismic.KeyTextField

  /**
   * Social Media Preview (uses default image if unset) field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: Meta & SEO
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, 'page', Lang>

/**
 * Item in *Podcast episode → Authors*
 */
export interface PodcastEpisodeDocumentDataAuthorsItem {
  /**
   * Name field in *Podcast episode → Authors*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: podcast_episode.authors[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField
}

type PodcastEpisodeDocumentDataBodySlice = never

/**
 * Content for Podcast episode documents
 */
interface PodcastEpisodeDocumentData {
  /**
   * Title field in *Podcast episode*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: podcast_episode.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField

  /**
   * Introduction field in *Podcast episode*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: podcast_episode.subline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subline: prismic.RichTextField

  /**
   * episode label field in *Podcast episode*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Episode
   * - **API ID Path**: podcast_episode.episode_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  episode_label: prismic.KeyTextField

  /**
   * Episode number field in *Podcast episode*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: podcast_episode.episode_number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  episode_number: prismic.NumberField

  /**
   * Authors field in *Podcast episode*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: podcast_episode.authors[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  authors: prismic.GroupField<Simplify<PodcastEpisodeDocumentDataAuthorsItem>>

  /**
   * duration field in *Podcast episode*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g.: 16min | 1h 02min
   * - **API ID Path**: podcast_episode.duration
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  duration: prismic.KeyTextField

  /**
   * Image field in *Podcast episode*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: podcast_episode.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Slice zone field in *Podcast episode*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: podcast_episode.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  body: prismic.SliceZone<PodcastEpisodeDocumentDataBodySlice> /**
                                                                * Meta title field in *Podcast episode*
                                                                *
                                                                * - **Field Type**: Text
                                                                * - **Placeholder**: Uses blog title if not set
                                                                * - **API ID Path**: podcast_episode.meta_title
                                                                * - **Tab**: Meta & SEO
                                                                * - **Documentation**: https://prismic.io/docs/field#key-text
                                                                */
  meta_title: prismic.KeyTextField

  /**
   * Meta description field in *Podcast episode*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Uses blog introduction if not set
   * - **API ID Path**: podcast_episode.meta_description
   * - **Tab**: Meta & SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta keywords field in *Podcast episode*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Uses default keywords if unset. Example: keyword1, keyword2, keyword3
   * - **API ID Path**: podcast_episode.meta_keywords
   * - **Tab**: Meta & SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_keywords: prismic.KeyTextField

  /**
   * Social Media Preview (uses blog image if unset) field in *Podcast episode*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: podcast_episode.meta_image
   * - **Tab**: Meta & SEO
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>
}

/**
 * Podcast episode document from Prismic
 *
 * - **API ID**: `podcast_episode`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PodcastEpisodeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PodcastEpisodeDocumentData>,
    'podcast_episode',
    Lang
  >

/**
 * Item in *Roadmap Entry → Goals*
 */
export interface RoadmapEntryDocumentDataGoalsItem {
  /**
   * Has flask icon? field in *Roadmap Entry → Goals*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: roadmap_entry.goals[].has_flask_icon
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  has_flask_icon: prismic.BooleanField

  /**
   * Title field in *Roadmap Entry → Goals*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: roadmap_entry.goals[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Description field in *Roadmap Entry → Goals*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: roadmap_entry.goals[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField
}

/**
 * Content for Roadmap Entry documents
 */
interface RoadmapEntryDocumentData {
  /**
   * Year label field in *Roadmap Entry*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 2022 & Beyond
   * - **API ID Path**: roadmap_entry.year_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  year_label: prismic.KeyTextField

  /**
   * Date field in *Roadmap Entry*
   *
   * - **Field Type**: Date
   * - **Placeholder**: Used to sort roadmap entries
   * - **API ID Path**: roadmap_entry.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField

  /**
   * workInProgress field in *Roadmap Entry*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: roadmap_entry.work_in_progress
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  work_in_progress: prismic.BooleanField

  /**
   * Goals field in *Roadmap Entry*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: roadmap_entry.goals[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  goals: prismic.GroupField<Simplify<RoadmapEntryDocumentDataGoalsItem>>
}

/**
 * Roadmap Entry document from Prismic
 *
 * - **API ID**: `roadmap_entry`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RoadmapEntryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<RoadmapEntryDocumentData>,
    'roadmap_entry',
    Lang
  >

interface TestDocumentData {}

/**
 * test document from Prismic
 *
 * - **API ID**: `test`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<TestDocumentData>, 'test', Lang>

export type AllDocumentTypes =
  | BlogPageDocument
  | ChildPageDocument
  | HomeDocument
  | Home2024Document
  | NavigationDocument
  | NimiqAppDocument
  | NimiqEventDocument
  | PageDocument
  | PodcastEpisodeDocument
  | RoadmapEntryDocument
  | TestDocument

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>
  }

  namespace Content {
    export type {
      AllDocumentTypes,
      BlogPageDocument,
      BlogPageDocumentData,
      BlogPageDocumentDataAuthorsItem,
      BlogPageDocumentDataBodySlice,
      ChildPageDocument,
      ChildPageDocumentData,
      ChildPageDocumentDataSlicesSlice,
      Home2024Document,
      Home2024DocumentData,
      Home2024DocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataBodySlice,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataAndMoreLinksItem,
      NavigationDocumentDataAppsAdditionalFooterLinksItem,
      NavigationDocumentDataAppsLinksItem,
      NavigationDocumentDataCommunityAdditionalFooterLinksItem,
      NavigationDocumentDataCommunityLinksItem,
      NavigationDocumentDataExtraHeaderLinksItem,
      NavigationDocumentDataGetStartedAdditionalFooterLinksItem,
      NavigationDocumentDataGetStartedLinksItem,
      NavigationDocumentDataHowToLinksItem,
      NavigationDocumentDataLegalPagesItem,
      NavigationDocumentDataNewToCryptoLinksItem,
      NavigationDocumentDataProjectAdditionalFooterLinksItem,
      NavigationDocumentDataProjectLinksItem,
      NavigationDocumentDataTechAdditionalFooterLinksItem,
      NavigationDocumentDataTechLinksItem,
      NimiqAppDocument,
      NimiqAppDocumentData,
      NimiqEventDocument,
      NimiqEventDocumentData,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PodcastEpisodeDocument,
      PodcastEpisodeDocumentData,
      PodcastEpisodeDocumentDataAuthorsItem,
      PodcastEpisodeDocumentDataBodySlice,
      RoadmapEntryDocument,
      RoadmapEntryDocumentData,
      RoadmapEntryDocumentDataGoalsItem,
      TestDocument,
      TestDocumentData,
    }
  }
}
