name: Deploy to NuxtHub
on: push

jobs:
  deploy:
    name: Deploy to NuxtHub
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}
      url: ${{ steps.deploy.outputs.deployment-url }}
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install
        env:
          PRISMIC_ACCESS_TOKEN: ${{ secrets.PRISMIC_ACCESS_TOKEN }}

      - name: Ensure NuxtHub module is installed
        run: pnpx nuxthub@latest ensure
        env:
          PRISMIC_ACCESS_TOKEN: ${{ secrets.PRISMIC_ACCESS_TOKEN }}

      - name: Set environment type
        run: echo "NUXTHUB_ENV=${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}" >> $GITHUB_ENV

      - name: Build application
        run: pnpm build:nuxthub
        env:
          # Secret variables
          NUXT_ALBATROSS_NODE_RPC_URL: ${{ secrets.NUXT_ALBATROSS_NODE_RPC_URL }}
          NUXT_PUBLIC_SUPABASE_KEY: ${{ secrets.NUXT_PUBLIC_SUPABASE_KEY }}
          NUXT_ZOHO_CLIENT_ID: ${{ secrets.NUXT_ZOHO_CLIENT_ID }}
          NUXT_ZOHO_CLIENT_SECRET: ${{ secrets.NUXT_ZOHO_CLIENT_SECRET }}
          NUXT_ZOHO_CODE: ${{ secrets.NUXT_ZOHO_CODE }}
          NUXT_ZOHO_LISTKEY: ${{ secrets.NUXT_ZOHO_LISTKEY }}
          NUXT_ZOHO_REFRESH_TOKEN: ${{ secrets.NUXT_ZOHO_REFRESH_TOKEN }}
          PRISMIC_ACCESS_TOKEN: ${{ secrets.PRISMIC_ACCESS_TOKEN }}

          # Variables
          NUXT_HUB_ENV: ${{ vars.NUXT_HUB_ENV }}
          NUXT_HUB_PROJECT_KEY: ${{ vars.NUXT_HUB_PROJECT_KEY }}
          NUXT_PUBLIC_SUPABASE_URL: ${{ vars.NUXT_PUBLIC_SUPABASE_URL }}
          NUXT_PUBLIC_VALIDATORS_API: ${{ vars.NUXT_PUBLIC_VALIDATORS_API }}
          NUXT_SITE_ENV: ${{ vars.NUXT_SITE_ENV }}
          NUXT_ZOHO_REQUEST_URL: ${{ vars.NUXT_ZOHO_REQUEST_URL }}
          NUXT_ZOHO_SCOPE: ${{ vars.NUXT_ZOHO_SCOPE }}

      - name: Deploy to NuxtHub
        uses: nuxt-hub/action@v1
        id: deploy
        with:
          project-key: nimiq-website-iem5
