// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  albatross_liveview: defineAsyncComponent(
    () => import("./AlbatrossLiveview/index.vue"),
  ),
  albatross_technical_details: defineAsyncComponent(
    () => import("./AlbatrossTechnicalDetails/index.vue"),
  ),
  app_gallery: defineAsyncComponent(() => import("./AppGalleryCta/index.vue")),
  apps_showcase: defineAsyncComponent(() => import("./AppsShowcase/index.vue")),
  banner_slice: defineAsyncComponent(() => import("./BannerSlice/index.vue")),
  blogposts_grid: defineAsyncComponent(
    () => import("./BlogpostsGrid/index.vue"),
  ),
  buy_sell_wallet: defineAsyncComponent(
    () => import("./BuySellWallet/index.vue"),
  ),
  cards_carousel: defineAsyncComponent(
    () => import("./CardsCarousel/index.vue"),
  ),
  consensus_map: defineAsyncComponent(() => import("./ConsensusMap/index.vue")),
  contact_form: defineAsyncComponent(() => import("./ContactForm/index.vue")),
  crypto_map_continent_selector: defineAsyncComponent(
    () => import("./CryptoMapContinentSelector/index.vue"),
  ),
  cta_section: defineAsyncComponent(() => import("./CtaSection/index.vue")),
  currency_comparison: defineAsyncComponent(
    () => import("./CurrencyComparison/index.vue"),
  ),
  exchanges_grid: defineAsyncComponent(
    () => import("./ExchangesGrid/index.vue"),
  ),
  exchanges_showcase: defineAsyncComponent(
    () => import("./ExchangesShowcase/index.vue"),
  ),
  flags_marquee: defineAsyncComponent(() => import("./FlagsMarquee/index.vue")),
  grid_section: defineAsyncComponent(() => import("./GridSection/index.vue")),
  hero_section: defineAsyncComponent(() => import("./HeroSection/index.vue")),
  hero_stats: defineAsyncComponent(() => import("./HeroStats/index.vue")),
  large_grid: defineAsyncComponent(() => import("./LargeGrid/index.vue")),
  latest_blogpost: defineAsyncComponent(
    () => import("./LatestBlogpost/index.vue"),
  ),
  link_grid: defineAsyncComponent(() => import("./LinkGrid/index.vue")),
  logos_grid: defineAsyncComponent(() => import("./LogosGrid/index.vue")),
  lottie_slice: defineAsyncComponent(() => import("./LottieSlice/index.vue")),
  new_york_grid: defineAsyncComponent(() => import("./NewYorkGrid/index.vue")),
  newsletter_form: defineAsyncComponent(
    () => import("./NewsletterForm/index.vue"),
  ),
  newsletter_subscription: defineAsyncComponent(
    () => import("./NewsletterSubscription/index.vue"),
  ),
  nim_token_distribution: defineAsyncComponent(
    () => import("./NimTokenDistribution/index.vue"),
  ),
  nimiq_wallet_hoverable: defineAsyncComponent(
    () => import("./NimiqWalletHoverable/index.vue"),
  ),
  pill_link: defineAsyncComponent(() => import("./PillLink/index.vue")),
  prestaking_grid: defineAsyncComponent(
    () => import("./PrestakingGrid/index.vue"),
  ),
  puzzle_grid: defineAsyncComponent(() => import("./PuzzleGrid/index.vue")),
  quote: defineAsyncComponent(() => import("./Quote/index.vue")),
  rich_text: defineAsyncComponent(() => import("./RichText/index.vue")),
  rich_text_cards: defineAsyncComponent(
    () => import("./RichTextCards/index.vue"),
  ),
  rich_text_carousel: defineAsyncComponent(
    () => import("./RichTextCarousel/index.vue"),
  ),
  roadmap: defineAsyncComponent(() => import("./Roadmap/index.vue")),
  simple_carousel: defineAsyncComponent(
    () => import("./SimpleCarousel/index.vue"),
  ),
  simple_headline: defineAsyncComponent(
    () => import("./SimpleHeadline/index.vue"),
  ),
  social_media_grid: defineAsyncComponent(
    () => import("./SocialMediaGrid/index.vue"),
  ),
  staking_calculator: defineAsyncComponent(
    () => import("./StakingCalculator/index.vue"),
  ),
  staking_distribution: defineAsyncComponent(
    () => import("./StakingDistribution/index.vue"),
  ),
  staking_faq: defineAsyncComponent(() => import("./StakingFaq/index.vue")),
  staking_slice: defineAsyncComponent(() => import("./StakingSlice/index.vue")),
  stepped_lottie: defineAsyncComponent(
    () => import("./SteppedLottie/index.vue"),
  ),
  stepped_slides: defineAsyncComponent(
    () => import("./SteppedSlides/index.vue"),
  ),
  team_members: defineAsyncComponent(() => import("./TeamMembers/index.vue")),
  tilted_media: defineAsyncComponent(() => import("./TiltedMedia/index.vue")),
  validator_list: defineAsyncComponent(
    () => import("./ValidatorList/index.vue"),
  ),
  vertical_video: defineAsyncComponent(
    () => import("./VerticalVideo/index.vue"),
  ),
  wallet_playground: defineAsyncComponent(
    () => import("./WalletPlayground/index.vue"),
  ),
  wallet_words_challenge: defineAsyncComponent(
    () => import("./WalletWordsChallenge/index.vue"),
  ),
  whitepaper_slice: defineAsyncComponent(
    () => import("./WhitepaperSlice/index.vue"),
  ),
  youtube_video: defineAsyncComponent(() => import("./YoutubeVideo/index.vue")),
  zig_zag_content: defineAsyncComponent(
    () => import("./ZigZagContent/index.vue"),
  ),
});
